#
# based on https://github.com/actions/setup-java
#
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11, 17 ]
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.12.0

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Rename the package
        run: mkdir artifacts && mv $(find build/distributions -name rpki-ta-0\*.zip) artifacts/rpki-ta-0.zip

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: artifacts        

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.12.0

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Execute Gradle build
        run: ./gradlew jib
