name: Release Upload
on:
  release:
    types: [ "published" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}  

    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.12.0

      - name: Rename the package
        run: mv $(find build/distributions -name rpki-ta-0\*.tgz) rpki-ta-0-java-11.tgz

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: rpki-ta-0-java-11.tgz
          asset_name: rpki-ta-0-java-11.tgz
          tag: ${{ github.ref }}

