name: Release

on:
  push:
    tags: 'rpki-ta-0-*'

jobs:
  build:
    if: github.repository == 'RIPE-NCC/rpki-ta-0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.12.0
  
      - name: Execute Gradle build
        run: ./gradlew build
  
      - name: Rename the package
        run: mv $(find build/distributions -name rpki-ta-0\*.tgz) ${{github.ref_name}}-java-11.tgz
  
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.ref_name}}-java-11.tgz
          draft: true
          body: It needs to be filled in manually
      
